/**
 *  Data from the IANA Time Zone Database https://www.iana.org/time-zones
 *  version 2021a (Released 2021-01-24) 
 */

/**
 * map ISO 3166-1 alpha-2 country codes to the names
 */
const countryCodeToName = {
  'AD': 'Andorra',
  'AE': 'United Arab Emirates',
  'AF': 'Afghanistan',
  'AG': 'Antigua & Barbuda',
  'AI': 'Anguilla',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AO': 'Angola',
  'AQ': 'Antarctica',
  'AR': 'Argentina',
  'AS': 'Samoa (American)',
  'AT': 'Austria',
  'AU': 'Australia',
  'AW': 'Aruba',
  'AX': 'land Islands',
  'AZ': 'Azerbaijan',
  'BA': 'Bosnia & Herzegovina',
  'BB': 'Barbados',
  'BD': 'Bangladesh',
  'BE': 'Belgium',
  'BF': 'Burkina Faso',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BI': 'Burundi',
  'BJ': 'Benin',
  'BL': 'St Barthelemy',
  'BM': 'Bermuda',
  'BN': 'Brunei',
  'BO': 'Bolivia',
  'BQ': 'Caribbean NL',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BT': 'Bhutan',
  'BV': 'Bouvet Island',
  'BW': 'Botswana',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'CA': 'Canada',
  'CC': 'Cocos (Keeling) Islands',
  'CD': 'Congo (Dem. Rep.)',
  'CF': 'Central African Rep.',
  'CG': 'Congo (Rep.)',
  'CH': 'Switzerland',
  'CI': 'Côte d\'Ivoire',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CV': 'Cape Verde',
  'CW': 'Curaçao',
  'CX': 'Christmas Island',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DK': 'Denmark',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'EH': 'Western Sahara',
  'ER': 'Eritrea',
  'ES': 'Spain',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FK': 'Falkland Islands',
  'FM': 'Micronesia',
  'FO': 'Faroe Islands',
  'FR': 'France',
  'GA': 'Gabon',
  'GB': 'Britain (UK)',
  'GD': 'Grenada',
  'GE': 'Georgia',
  'GF': 'French Guiana',
  'GG': 'Guernsey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Greenland',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GP': 'Guadeloupe',
  'GQ': 'Equatorial Guinea',
  'GR': 'Greece',
  'GS': 'South Georgia & the South Sandwich Islands',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HM': 'Heard Island & McDonald Islands',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IM': 'Isle of Man',
  'IN': 'India',
  'IO': 'British Indian Ocean Territory',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JE': 'Jersey',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KH': 'Cambodia',
  'KI': 'Kiribati',
  'KM': 'Comoros',
  'KN': 'St Kitts & Nevis',
  'KP': 'Korea (North)',
  'KR': 'Korea (South)',
  'KW': 'Kuwait',
  'KY': 'Cayman Islands',
  'KZ': 'Kazakhstan',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LC': 'St Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'LY': 'Libya',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldova',
  'ME': 'Montenegro',
  'MF': 'St Martin (French)',
  'MG': 'Madagascar',
  'MH': 'Marshall Islands',
  'MK': 'North Macedonia',
  'ML': 'Mali',
  'MM': 'Myanmar (Burma)',
  'MN': 'Mongolia',
  'MO': 'Macau',
  'MP': 'Northern Mariana Islands',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MW': 'Malawi',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NC': 'New Caledonia',
  'NE': 'Niger',
  'NF': 'Norfolk Island',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NU': 'Niue',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'French Polynesia',
  'PG': 'Papua New Guinea',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Poland',
  'PM': 'St Pierre & Miquelon',
  'PN': 'Pitcairn',
  'PR': 'Puerto Rico',
  'PS': 'Palestine',
  'PT': 'Portugal',
  'PW': 'Palau',
  'PY': 'Paraguay',
  'QA': 'Qatar',
  'RE': 'Réunion',
  'RO': 'Romania',
  'RS': 'Serbia',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SA': 'Saudi Arabia',
  'SB': 'Solomon Islands',
  'SC': 'Seychelles',
  'SD': 'Sudan',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'SH': 'St Helena',
  'SI': 'Slovenia',
  'SJ': 'Svalbard & Jan Mayen',
  'SK': 'Slovakia',
  'SL': 'Sierra Leone',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Suriname',
  'SS': 'South Sudan',
  'ST': 'Sao Tome & Principe',
  'SV': 'El Salvador',
  'SX': 'St Maarten (Dutch)',
  'SY': 'Syria',
  'SZ': 'Eswatini (Swaziland)',
  'TC': 'Turks & Caicos Is',
  'TD': 'Chad',
  'TF': 'French Southern & Antarctic Lands',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TK': 'Tokelau',
  'TL': 'East Timor',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TR': 'Turkey',
  'TT': 'Trinidad & Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'UM': 'US minor outlying islands',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VA': 'Vatican City',
  'VC': 'St Vincent',
  'VE': 'Venezuela',
  'VG': 'Virgin Islands (UK)',
  'VI': 'Virgin Islands (US)',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis & Futuna',
  'WS': 'Samoa (western)',
  'YE': 'Yemen',
  'YT': 'Mayotte',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe'
}

const tzToCountryCode = {
  'Europe/Andorra': [ 'AD' ],
  'Asia/Dubai': [ 'AE', 'OM' ],
  'Asia/Kabul': [ 'AF' ],
  'Europe/Tirane': [ 'AL' ],
  'Asia/Yerevan': [ 'AM' ],
  'Antarctica/Casey': [ 'AQ' ],
  'Antarctica/Davis': [ 'AQ' ],
  'Antarctica/DumontDUrville': [ 'AQ' ],
  'Antarctica/Mawson': [ 'AQ' ],
  'Antarctica/Palmer': [ 'AQ' ],
  'Antarctica/Rothera': [ 'AQ' ],
  'Antarctica/Syowa': [ 'AQ' ],
  'Antarctica/Troll': [ 'AQ' ],
  'Antarctica/Vostok': [ 'AQ' ],
  'America/Argentina/Buenos_Aires': [ 'AR' ],
  'America/Argentina/Cordoba': [ 'AR' ],
  'America/Argentina/Salta': [ 'AR' ],
  'America/Argentina/Jujuy': [ 'AR' ],
  'America/Argentina/Tucuman': [ 'AR' ],
  'America/Argentina/Catamarca': [ 'AR' ],
  'America/Argentina/La_Rioja': [ 'AR' ],
  'America/Argentina/San_Juan': [ 'AR' ],
  'America/Argentina/Mendoza': [ 'AR' ],
  'America/Argentina/San_Luis': [ 'AR' ],
  'America/Argentina/Rio_Gallegos': [ 'AR' ],
  'America/Argentina/Ushuaia': [ 'AR' ],
  'Pacific/Pago_Pago': [ 'AS', 'UM' ],
  'Europe/Vienna': [ 'AT' ],
  'Australia/Lord_Howe': [ 'AU' ],
  'Antarctica/Macquarie': [ 'AU' ],
  'Australia/Hobart': [ 'AU' ],
  'Australia/Melbourne': [ 'AU' ],
  'Australia/Sydney': [ 'AU' ],
  'Australia/Broken_Hill': [ 'AU' ],
  'Australia/Brisbane': [ 'AU' ],
  'Australia/Lindeman': [ 'AU' ],
  'Australia/Adelaide': [ 'AU' ],
  'Australia/Darwin': [ 'AU' ],
  'Australia/Perth': [ 'AU' ],
  'Australia/Eucla': [ 'AU' ],
  'Asia/Baku': [ 'AZ' ],
  'America/Barbados': [ 'BB' ],
  'Asia/Dhaka': [ 'BD' ],
  'Europe/Brussels': [ 'BE' ],
  'Europe/Sofia': [ 'BG' ],
  'Atlantic/Bermuda': [ 'BM' ],
  'Asia/Brunei': [ 'BN' ],
  'America/La_Paz': [ 'BO' ],
  'America/Noronha': [ 'BR' ],
  'America/Belem': [ 'BR' ],
  'America/Fortaleza': [ 'BR' ],
  'America/Recife': [ 'BR' ],
  'America/Araguaina': [ 'BR' ],
  'America/Maceio': [ 'BR' ],
  'America/Bahia': [ 'BR' ],
  'America/Sao_Paulo': [ 'BR' ],
  'America/Campo_Grande': [ 'BR' ],
  'America/Cuiaba': [ 'BR' ],
  'America/Santarem': [ 'BR' ],
  'America/Porto_Velho': [ 'BR' ],
  'America/Boa_Vista': [ 'BR' ],
  'America/Manaus': [ 'BR' ],
  'America/Eirunepe': [ 'BR' ],
  'America/Rio_Branco': [ 'BR' ],
  'America/Nassau': [ 'BS' ],
  'Asia/Thimphu': [ 'BT' ],
  'Europe/Minsk': [ 'BY' ],
  'America/Belize': [ 'BZ' ],
  'America/St_Johns': [ 'CA' ],
  'America/Halifax': [ 'CA' ],
  'America/Glace_Bay': [ 'CA' ],
  'America/Moncton': [ 'CA' ],
  'America/Goose_Bay': [ 'CA' ],
  'America/Blanc-Sablon': [ 'CA' ],
  'America/Toronto': [ 'CA' ],
  'America/Nipigon': [ 'CA' ],
  'America/Thunder_Bay': [ 'CA' ],
  'America/Iqaluit': [ 'CA' ],
  'America/Pangnirtung': [ 'CA' ],
  'America/Atikokan': [ 'CA' ],
  'America/Winnipeg': [ 'CA' ],
  'America/Rainy_River': [ 'CA' ],
  'America/Resolute': [ 'CA' ],
  'America/Rankin_Inlet': [ 'CA' ],
  'America/Regina': [ 'CA' ],
  'America/Swift_Current': [ 'CA' ],
  'America/Edmonton': [ 'CA' ],
  'America/Cambridge_Bay': [ 'CA' ],
  'America/Yellowknife': [ 'CA' ],
  'America/Inuvik': [ 'CA' ],
  'America/Creston': [ 'CA' ],
  'America/Dawson_Creek': [ 'CA' ],
  'America/Fort_Nelson': [ 'CA' ],
  'America/Whitehorse': [ 'CA' ],
  'America/Dawson': [ 'CA' ],
  'America/Vancouver': [ 'CA' ],
  'Indian/Cocos': [ 'CC' ],
  'Europe/Zurich': [ 'CH', 'DE', 'LI' ],
  'Africa/Abidjan': [
    'CI', 'BF', 'GM',
    'GN', 'ML', 'MR',
    'SH', 'SL', 'SN',
    'TG'
  ],
  'Pacific/Rarotonga': [ 'CK' ],
  'America/Santiago': [ 'CL' ],
  'America/Punta_Arenas': [ 'CL' ],
  'Pacific/Easter': [ 'CL' ],
  'Asia/Shanghai': [ 'CN' ],
  'Asia/Urumqi': [ 'CN' ],
  'America/Bogota': [ 'CO' ],
  'America/Costa_Rica': [ 'CR' ],
  'America/Havana': [ 'CU' ],
  'Atlantic/Cape_Verde': [ 'CV' ],
  'America/Curacao': [ 'CW', 'AW', 'BQ', 'SX' ],
  'Indian/Christmas': [ 'CX' ],
  'Asia/Nicosia': [ 'CY' ],
  'Asia/Famagusta': [ 'CY' ],
  'Europe/Prague': [ 'CZ', 'SK' ],
  'Europe/Berlin': [ 'DE' ],
  'Europe/Copenhagen': [ 'DK' ],
  'America/Santo_Domingo': [ 'DO' ],
  'Africa/Algiers': [ 'DZ' ],
  'America/Guayaquil': [ 'EC' ],
  'Pacific/Galapagos': [ 'EC' ],
  'Europe/Tallinn': [ 'EE' ],
  'Africa/Cairo': [ 'EG' ],
  'Africa/El_Aaiun': [ 'EH' ],
  'Europe/Madrid': [ 'ES' ],
  'Africa/Ceuta': [ 'ES' ],
  'Atlantic/Canary': [ 'ES' ],
  'Europe/Helsinki': [ 'FI', 'AX' ],
  'Pacific/Fiji': [ 'FJ' ],
  'Atlantic/Stanley': [ 'FK' ],
  'Pacific/Chuuk': [ 'FM' ],
  'Pacific/Pohnpei': [ 'FM' ],
  'Pacific/Kosrae': [ 'FM' ],
  'Atlantic/Faroe': [ 'FO' ],
  'Europe/Paris': [ 'FR' ],
  'Europe/London': [ 'GB', 'GG', 'IM', 'JE' ],
  'Asia/Tbilisi': [ 'GE' ],
  'America/Cayenne': [ 'GF' ],
  'Africa/Accra': [ 'GH' ],
  'Europe/Gibraltar': [ 'GI' ],
  'America/Nuuk': [ 'GL' ],
  'America/Danmarkshavn': [ 'GL' ],
  'America/Scoresbysund': [ 'GL' ],
  'America/Thule': [ 'GL' ],
  'Europe/Athens': [ 'GR' ],
  'Atlantic/South_Georgia': [ 'GS' ],
  'America/Guatemala': [ 'GT' ],
  'Pacific/Guam': [ 'GU', 'MP' ],
  'Africa/Bissau': [ 'GW' ],
  'America/Guyana': [ 'GY' ],
  'Asia/Hong_Kong': [ 'HK' ],
  'America/Tegucigalpa': [ 'HN' ],
  'America/Port-au-Prince': [ 'HT' ],
  'Europe/Budapest': [ 'HU' ],
  'Asia/Jakarta': [ 'ID' ],
  'Asia/Pontianak': [ 'ID' ],
  'Asia/Makassar': [ 'ID' ],
  'Asia/Jayapura': [ 'ID' ],
  'Europe/Dublin': [ 'IE' ],
  'Asia/Jerusalem': [ 'IL' ],
  'Asia/Kolkata': [ 'IN' ],
  'Indian/Chagos': [ 'IO' ],
  'Asia/Baghdad': [ 'IQ' ],
  'Asia/Tehran': [ 'IR' ],
  'Atlantic/Reykjavik': [ 'IS' ],
  'Europe/Rome': [ 'IT', 'SM', 'VA' ],
  'America/Jamaica': [ 'JM' ],
  'Asia/Amman': [ 'JO' ],
  'Asia/Tokyo': [ 'JP' ],
  'Africa/Nairobi': [
    'KE', 'DJ', 'ER',
    'ET', 'KM', 'MG',
    'SO', 'TZ', 'UG',
    'YT'
  ],
  'Asia/Bishkek': [ 'KG' ],
  'Pacific/Tarawa': [ 'KI' ],
  'Pacific/Enderbury': [ 'KI' ],
  'Pacific/Kiritimati': [ 'KI' ],
  'Asia/Pyongyang': [ 'KP' ],
  'Asia/Seoul': [ 'KR' ],
  'Asia/Almaty': [ 'KZ' ],
  'Asia/Qyzylorda': [ 'KZ' ],
  'Asia/Qostanay': [ 'KZ' ],
  'Asia/Aqtobe': [ 'KZ' ],
  'Asia/Aqtau': [ 'KZ' ],
  'Asia/Atyrau': [ 'KZ' ],
  'Asia/Oral': [ 'KZ' ],
  'Asia/Beirut': [ 'LB' ],
  'Asia/Colombo': [ 'LK' ],
  'Africa/Monrovia': [ 'LR' ],
  'Europe/Vilnius': [ 'LT' ],
  'Europe/Luxembourg': [ 'LU' ],
  'Europe/Riga': [ 'LV' ],
  'Africa/Tripoli': [ 'LY' ],
  'Africa/Casablanca': [ 'MA' ],
  'Europe/Monaco': [ 'MC' ],
  'Europe/Chisinau': [ 'MD' ],
  'Pacific/Majuro': [ 'MH' ],
  'Pacific/Kwajalein': [ 'MH' ],
  'Asia/Yangon': [ 'MM' ],
  'Asia/Ulaanbaatar': [ 'MN' ],
  'Asia/Hovd': [ 'MN' ],
  'Asia/Choibalsan': [ 'MN' ],
  'Asia/Macau': [ 'MO' ],
  'America/Martinique': [ 'MQ' ],
  'Europe/Malta': [ 'MT' ],
  'Indian/Mauritius': [ 'MU' ],
  'Indian/Maldives': [ 'MV' ],
  'America/Mexico_City': [ 'MX' ],
  'America/Cancun': [ 'MX' ],
  'America/Merida': [ 'MX' ],
  'America/Monterrey': [ 'MX' ],
  'America/Matamoros': [ 'MX' ],
  'America/Mazatlan': [ 'MX' ],
  'America/Chihuahua': [ 'MX' ],
  'America/Ojinaga': [ 'MX' ],
  'America/Hermosillo': [ 'MX' ],
  'America/Tijuana': [ 'MX' ],
  'America/Bahia_Banderas': [ 'MX' ],
  'Asia/Kuala_Lumpur': [ 'MY' ],
  'Asia/Kuching': [ 'MY' ],
  'Africa/Maputo': [
    'MZ', 'BI', 'BW',
    'CD', 'MW', 'RW',
    'ZM', 'ZW'
  ],
  'Africa/Windhoek': [ 'NA' ],
  'Pacific/Noumea': [ 'NC' ],
  'Pacific/Norfolk': [ 'NF' ],
  'Africa/Lagos': [
    'NG', 'AO', 'BJ',
    'CD', 'CF', 'CG',
    'CM', 'GA', 'GQ',
    'NE'
  ],
  'America/Managua': [ 'NI' ],
  'Europe/Amsterdam': [ 'NL' ],
  'Europe/Oslo': [ 'NO', 'SJ' ],
  'Asia/Kathmandu': [ 'NP' ],
  'Pacific/Nauru': [ 'NR' ],
  'Pacific/Niue': [ 'NU' ],
  'Pacific/Auckland': [ 'NZ', 'AQ' ],
  'Pacific/Chatham': [ 'NZ' ],
  'America/Panama': [ 'PA', 'KY' ],
  'America/Lima': [ 'PE' ],
  'Pacific/Tahiti': [ 'PF' ],
  'Pacific/Marquesas': [ 'PF' ],
  'Pacific/Gambier': [ 'PF' ],
  'Pacific/Port_Moresby': [ 'PG' ],
  'Pacific/Bougainville': [ 'PG' ],
  'Asia/Manila': [ 'PH' ],
  'Asia/Karachi': [ 'PK' ],
  'Europe/Warsaw': [ 'PL' ],
  'America/Miquelon': [ 'PM' ],
  'Pacific/Pitcairn': [ 'PN' ],
  'America/Puerto_Rico': [ 'PR' ],
  'Asia/Gaza': [ 'PS' ],
  'Asia/Hebron': [ 'PS' ],
  'Europe/Lisbon': [ 'PT' ],
  'Atlantic/Madeira': [ 'PT' ],
  'Atlantic/Azores': [ 'PT' ],
  'Pacific/Palau': [ 'PW' ],
  'America/Asuncion': [ 'PY' ],
  'Asia/Qatar': [ 'QA', 'BH' ],
  'Indian/Reunion': [ 'RE', 'TF' ],
  'Europe/Bucharest': [ 'RO' ],
  'Europe/Belgrade': [ 'RS', 'BA', 'HR', 'ME', 'MK', 'SI' ],
  'Europe/Kaliningrad': [ 'RU' ],
  'Europe/Moscow': [ 'RU' ],
  'Europe/Simferopol': [ 'RU', 'UA' ],
  'Europe/Kirov': [ 'RU' ],
  'Europe/Volgograd': [ 'RU' ],
  'Europe/Astrakhan': [ 'RU' ],
  'Europe/Saratov': [ 'RU' ],
  'Europe/Ulyanovsk': [ 'RU' ],
  'Europe/Samara': [ 'RU' ],
  'Asia/Yekaterinburg': [ 'RU' ],
  'Asia/Omsk': [ 'RU' ],
  'Asia/Novosibirsk': [ 'RU' ],
  'Asia/Barnaul': [ 'RU' ],
  'Asia/Tomsk': [ 'RU' ],
  'Asia/Novokuznetsk': [ 'RU' ],
  'Asia/Krasnoyarsk': [ 'RU' ],
  'Asia/Irkutsk': [ 'RU' ],
  'Asia/Chita': [ 'RU' ],
  'Asia/Yakutsk': [ 'RU' ],
  'Asia/Khandyga': [ 'RU' ],
  'Asia/Vladivostok': [ 'RU' ],
  'Asia/Ust-Nera': [ 'RU' ],
  'Asia/Magadan': [ 'RU' ],
  'Asia/Sakhalin': [ 'RU' ],
  'Asia/Srednekolymsk': [ 'RU' ],
  'Asia/Kamchatka': [ 'RU' ],
  'Asia/Anadyr': [ 'RU' ],
  'Asia/Riyadh': [ 'SA', 'KW', 'YE' ],
  'Pacific/Guadalcanal': [ 'SB' ],
  'Indian/Mahe': [ 'SC' ],
  'Africa/Khartoum': [ 'SD' ],
  'Europe/Stockholm': [ 'SE' ],
  'Asia/Singapore': [ 'SG' ],
  'America/Paramaribo': [ 'SR' ],
  'Africa/Juba': [ 'SS' ],
  'Africa/Sao_Tome': [ 'ST' ],
  'America/El_Salvador': [ 'SV' ],
  'Asia/Damascus': [ 'SY' ],
  'America/Grand_Turk': [ 'TC' ],
  'Africa/Ndjamena': [ 'TD' ],
  'Indian/Kerguelen': [ 'TF' ],
  'Asia/Bangkok': [ 'TH', 'KH', 'LA', 'VN' ],
  'Asia/Dushanbe': [ 'TJ' ],
  'Pacific/Fakaofo': [ 'TK' ],
  'Asia/Dili': [ 'TL' ],
  'Asia/Ashgabat': [ 'TM' ],
  'Africa/Tunis': [ 'TN' ],
  'Pacific/Tongatapu': [ 'TO' ],
  'Europe/Istanbul': [ 'TR' ],
  'America/Port_of_Spain': [
    'TT', 'AG', 'AI',
    'BL', 'DM', 'GD',
    'GP', 'KN', 'LC',
    'MF', 'MS', 'VC',
    'VG', 'VI'
  ],
  'Pacific/Funafuti': [ 'TV' ],
  'Asia/Taipei': [ 'TW' ],
  'Europe/Kiev': [ 'UA' ],
  'Europe/Uzhgorod': [ 'UA' ],
  'Europe/Zaporozhye': [ 'UA' ],
  'Pacific/Wake': [ 'UM' ],
  'America/New_York': [ 'US' ],
  'America/Detroit': [ 'US' ],
  'America/Kentucky/Louisville': [ 'US' ],
  'America/Kentucky/Monticello': [ 'US' ],
  'America/Indiana/Indianapolis': [ 'US' ],
  'America/Indiana/Vincennes': [ 'US' ],
  'America/Indiana/Winamac': [ 'US' ],
  'America/Indiana/Marengo': [ 'US' ],
  'America/Indiana/Petersburg': [ 'US' ],
  'America/Indiana/Vevay': [ 'US' ],
  'America/Chicago': [ 'US' ],
  'America/Indiana/Tell_City': [ 'US' ],
  'America/Indiana/Knox': [ 'US' ],
  'America/Menominee': [ 'US' ],
  'America/North_Dakota/Center': [ 'US' ],
  'America/North_Dakota/New_Salem': [ 'US' ],
  'America/North_Dakota/Beulah': [ 'US' ],
  'America/Denver': [ 'US' ],
  'America/Boise': [ 'US' ],
  'America/Phoenix': [ 'US' ],
  'America/Los_Angeles': [ 'US' ],
  'America/Anchorage': [ 'US' ],
  'America/Juneau': [ 'US' ],
  'America/Sitka': [ 'US' ],
  'America/Metlakatla': [ 'US' ],
  'America/Yakutat': [ 'US' ],
  'America/Nome': [ 'US' ],
  'America/Adak': [ 'US' ],
  'Pacific/Honolulu': [ 'US', 'UM' ],
  'America/Montevideo': [ 'UY' ],
  'Asia/Samarkand': [ 'UZ' ],
  'Asia/Tashkent': [ 'UZ' ],
  'America/Caracas': [ 'VE' ],
  'Asia/Ho_Chi_Minh': [ 'VN' ],
  'Pacific/Efate': [ 'VU' ],
  'Pacific/Wallis': [ 'WF' ],
  'Pacific/Apia': [ 'WS' ],
  'Africa/Johannesburg': [ 'ZA', 'LS', 'SZ' ]
};

const tzNames = Object.keys(tzToCountryCode);

function getCountriesByTz(tzName: string): Array<{name: string, code: string}> {
  if (!tzToCountryCode[tzName]) {
    throw new Error(`Unknown timezone: ${tzName}`);
  }

  return tzToCountryCode[tzName].map(function (countryCode) {
    if (!countryCodeToName[countryCode]) {
      throw new Error(`Unknown country code: ${countryCode}`);
    }

    return {
      name: countryCodeToName[countryCode],
      code: countryCode
    };
  });
}

export {
  tzNames,
  getCountriesByTz
}